### ISSUE TITLE
Support other OAUTH / Identity Providers

### ISSUE THREAD

**Issue by arthuston** [awslabs/fhir-works-on-aws-authz-rbac#10]
The AWS FHIR Server implementation should use a plug-and-play approach so Cognito can be removed and replaced with another Auth provider.

AC:

- AWS FHIR Server can be configured to be used with Auth Providers other than Cognito.

**Comment by rsmayda** [comment]
Good callout here. A possible solution is to pass in claim's location information into the AuthZ constructor and remove all the explicit cognito references

**Comment by rsmayda** [comment]
We have now released SMART on FHIR support which is idP agnostic: https://github.com/awslabs/fhir-works-on-aws-authz-smart

Closing this issue. Please re-open if you have further questions

**Comment by shengc5** [comment]
Is there plan to support aforementioned plug-and-play implementation where SMART is not a requirement? i.e. mainline, but cognito is optional and can be swapped by other idP's? If not would love to get pointers on how this can be done easily. Thanks!
