### ISSUE TITLE
Check patient/*.read scope in APIs

### ISSUE THREAD

**Issue by arthuston** [awslabs/fhir-works-on-aws-authz-rbac#11]
Each FHIR Patient API has a set of required scopes. For read, this is patient/*.read; for writes, this is patient/*.read.

We need to map each API to the set of required scopes. Next, each API needs to get the scopes from the access token. If any required scope is missing, we need to return a Forbidden error. 

Next, we need to determine how to get the Id (patient id) associated with this record:

If the resource is Patient, this is the Id

if the resource has a reference to a Patient, this is the ID in the reference

If the patient is more than one level removed (for example a reference to a reference) we need to traverse the records.

After determining the id for the active Patient, we need to return an error or no data, depending on our security decision.

For lists, we need to filter all but the patient in patientContext.

**Comment by rsmayda** [comment]
Thanks for making an enhancement for this. Most likely SMART on FHIR AuthZ will become a new package. Will leave this open until then

**Comment by rsmayda** [comment]
SMART package now live: https://github.com/awslabs/fhir-works-on-aws-authz-smart

Please open SMART related issues there
